// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearSelectedToken(arg1) {
  return window['go']['services']['AppConfigService']['ClearSelectedToken'](arg1);
}

export function ClearTokenFromAllRepos(arg1) {
  return window['go']['services']['AppConfigService']['ClearTokenFromAllRepos'](arg1);
}

export function GetRecentRepositories() {
  return window['go']['services']['AppConfigService']['GetRecentRepositories']();
}

export function GetSelectedToken(arg1) {
  return window['go']['services']['AppConfigService']['GetSelectedToken'](arg1);
}

export function GetUIPreferences() {
  return window['go']['services']['AppConfigService']['GetUIPreferences']();
}

export function SaveUIPreferences(arg1) {
  return window['go']['services']['AppConfigService']['SaveUIPreferences'](arg1);
}

export function SetSelectedToken(arg1, arg2) {
  return window['go']['services']['AppConfigService']['SetSelectedToken'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['services']['AppConfigService']['Startup'](arg1);
}

export function UpdateRepositoryAccess(arg1, arg2) {
  return window['go']['services']['AppConfigService']['UpdateRepositoryAccess'](arg1, arg2);
}
