// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ArchiveChangelistGroup(arg1, arg2, arg3, arg4) {
  return window['go']['services']['ArchiveService']['ArchiveChangelistGroup'](arg1, arg2, arg3, arg4);
}

export function DeleteArchiveByName(arg1) {
  return window['go']['services']['ArchiveService']['DeleteArchiveByName'](arg1);
}

export function GetArchiveDiffContent(arg1) {
  return window['go']['services']['ArchiveService']['GetArchiveDiffContent'](arg1);
}

export function GetArchiveList() {
  return window['go']['services']['ArchiveService']['GetArchiveList']();
}

export function GetArchiveMetadata(arg1) {
  return window['go']['services']['ArchiveService']['GetArchiveMetadata'](arg1);
}

export function RenameArchiveByName(arg1, arg2) {
  return window['go']['services']['ArchiveService']['RenameArchiveByName'](arg1, arg2);
}

export function RestoreArchiveToWorkingTree(arg1, arg2) {
  return window['go']['services']['ArchiveService']['RestoreArchiveToWorkingTree'](arg1, arg2);
}

export function SetExecutor(arg1) {
  return window['go']['services']['ArchiveService']['SetExecutor'](arg1);
}

export function SetRepositoryPath(arg1) {
  return window['go']['services']['ArchiveService']['SetRepositoryPath'](arg1);
}

export function Startup(arg1) {
  return window['go']['services']['ArchiveService']['Startup'](arg1);
}
