// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {services} from '../models';
import {git} from '../models';
import {context} from '../models';

export function ArchiveChangelistGroup(arg1:models.Changelist,arg2:string,arg3:string,arg4:Array<string>):Promise<models.ArchiveMetadata>;

export function DeleteArchiveByName(arg1:string):Promise<void>;

export function GetArchiveDiffContent(arg1:string):Promise<string>;

export function GetArchiveList():Promise<Array<models.ArchiveListEntry>>;

export function GetArchiveMetadata(arg1:string):Promise<models.ArchiveMetadata>;

export function RenameArchiveByName(arg1:string,arg2:string):Promise<void>;

export function RestoreArchiveToWorkingTree(arg1:string,arg2:services.RestoreOptions):Promise<services.RestoreResult>;

export function SetExecutor(arg1:git.Executor):Promise<void>;

export function SetRepositoryPath(arg1:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
