// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {git} from '../models';
import {context} from '../models';

export function GetBlame(arg1:string):Promise<models.BlameResult>;

export function SetExecutor(arg1:git.Executor):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
