// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBlame(arg1) {
  return window['go']['services']['BlameService']['GetBlame'](arg1);
}

export function SetExecutor(arg1) {
  return window['go']['services']['BlameService']['SetExecutor'](arg1);
}

export function Startup(arg1) {
  return window['go']['services']['BlameService']['Startup'](arg1);
}
