// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {context} from '../models';

export function AddPathsToChangelistGroup(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function CreateChangelistGroup(arg1:string,arg2:string):Promise<models.Changelist>;

export function DeleteChangelistGroup(arg1:string,arg2:string):Promise<void>;

export function GetAllChangelistGroups(arg1:string):Promise<Array<models.Changelist>>;

export function MovePathsBetweenChangelistGroups(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<void>;

export function ReconcileChangelistsWithGitRepositoryStatus(arg1:string,arg2:string):Promise<void>;

export function RemoveMissingFilesFromAllGroups(arg1:string):Promise<number>;

export function RemovePathsFromChangelistGroup(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function RenameChangelistGroup(arg1:string,arg2:string,arg3:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
