// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddPathsToChangelistGroup(arg1, arg2, arg3) {
  return window['go']['services']['ChangelistService']['AddPathsToChangelistGroup'](arg1, arg2, arg3);
}

export function CreateChangelistGroup(arg1, arg2) {
  return window['go']['services']['ChangelistService']['CreateChangelistGroup'](arg1, arg2);
}

export function DeleteChangelistGroup(arg1, arg2) {
  return window['go']['services']['ChangelistService']['DeleteChangelistGroup'](arg1, arg2);
}

export function GetAllChangelistGroups(arg1) {
  return window['go']['services']['ChangelistService']['GetAllChangelistGroups'](arg1);
}

export function MovePathsBetweenChangelistGroups(arg1, arg2, arg3, arg4) {
  return window['go']['services']['ChangelistService']['MovePathsBetweenChangelistGroups'](arg1, arg2, arg3, arg4);
}

export function ReconcileChangelistsWithGitRepositoryStatus(arg1, arg2) {
  return window['go']['services']['ChangelistService']['ReconcileChangelistsWithGitRepositoryStatus'](arg1, arg2);
}

export function RemoveMissingFilesFromAllGroups(arg1) {
  return window['go']['services']['ChangelistService']['RemoveMissingFilesFromAllGroups'](arg1);
}

export function RemovePathsFromChangelistGroup(arg1, arg2, arg3) {
  return window['go']['services']['ChangelistService']['RemovePathsFromChangelistGroup'](arg1, arg2, arg3);
}

export function RenameChangelistGroup(arg1, arg2, arg3) {
  return window['go']['services']['ChangelistService']['RenameChangelistGroup'](arg1, arg2, arg3);
}

export function Startup(arg1) {
  return window['go']['services']['ChangelistService']['Startup'](arg1);
}
