// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearSelectedToken(arg1) {
  return window['go']['services']['ConfigService']['ClearSelectedToken'](arg1);
}

export function ClearTokenFromAllRepos(arg1) {
  return window['go']['services']['ConfigService']['ClearTokenFromAllRepos'](arg1);
}

export function GetRepositoryConfig(arg1) {
  return window['go']['services']['ConfigService']['GetRepositoryConfig'](arg1);
}

export function GetSelectedToken(arg1) {
  return window['go']['services']['ConfigService']['GetSelectedToken'](arg1);
}

export function SetSelectedToken(arg1, arg2) {
  return window['go']['services']['ConfigService']['SetSelectedToken'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['services']['ConfigService']['Startup'](arg1);
}
