// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddGitHubTokenWithRepo(arg1, arg2, arg3, arg4) {
  return window['go']['services']['CredentialsService']['AddGitHubTokenWithRepo'](arg1, arg2, arg3, arg4);
}

export function DeleteGitHubToken() {
  return window['go']['services']['CredentialsService']['DeleteGitHubToken']();
}

export function DeleteGitHubTokenWithRepo(arg1) {
  return window['go']['services']['CredentialsService']['DeleteGitHubTokenWithRepo'](arg1);
}

export function GetAllGitHubTokens() {
  return window['go']['services']['CredentialsService']['GetAllGitHubTokens']();
}

export function GetGitHubToken() {
  return window['go']['services']['CredentialsService']['GetGitHubToken']();
}

export function GetGitHubTokenByID(arg1) {
  return window['go']['services']['CredentialsService']['GetGitHubTokenByID'](arg1);
}

export function GetGitHubTokenForRepo(arg1) {
  return window['go']['services']['CredentialsService']['GetGitHubTokenForRepo'](arg1);
}

export function GetGitHubTokenForRepoWithSelection(arg1, arg2) {
  return window['go']['services']['CredentialsService']['GetGitHubTokenForRepoWithSelection'](arg1, arg2);
}

export function HasGitHubToken() {
  return window['go']['services']['CredentialsService']['HasGitHubToken']();
}

export function SetConfigService(arg1) {
  return window['go']['services']['CredentialsService']['SetConfigService'](arg1);
}

export function SetGitHubToken(arg1) {
  return window['go']['services']['CredentialsService']['SetGitHubToken'](arg1);
}

export function Startup(arg1) {
  return window['go']['services']['CredentialsService']['Startup'](arg1);
}

export function UpdateGitHubTokenWithRepo(arg1, arg2, arg3, arg4) {
  return window['go']['services']['CredentialsService']['UpdateGitHubTokenWithRepo'](arg1, arg2, arg3, arg4);
}
