// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {context} from '../models';

export function AddGitHubTokenWithRepo(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function DeleteGitHubToken():Promise<void>;

export function DeleteGitHubTokenWithRepo(arg1:string):Promise<void>;

export function GetAllGitHubTokens():Promise<Array<services.GitHubToken>>;

export function GetGitHubToken():Promise<string>;

export function GetGitHubTokenByID(arg1:string):Promise<services.GitHubToken>;

export function GetGitHubTokenForRepo(arg1:string):Promise<string>;

export function GetGitHubTokenForRepoWithSelection(arg1:string,arg2:string):Promise<string>;

export function HasGitHubToken():Promise<boolean>;

export function SetAppConfigService(arg1:services.AppConfigService):Promise<void>;

export function SetGitHubToken(arg1:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function UpdateGitHubTokenWithRepo(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;
