// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreatePatchFile(arg1, arg2) {
  return window['go']['services']['DiffService']['CreatePatchFile'](arg1, arg2);
}

export function CreatePatchFileForFiles(arg1, arg2) {
  return window['go']['services']['DiffService']['CreatePatchFileForFiles'](arg1, arg2);
}

export function GenerateDefaultPatchFileName(arg1) {
  return window['go']['services']['DiffService']['GenerateDefaultPatchFileName'](arg1);
}

export function GetChangelistGroupDiff(arg1) {
  return window['go']['services']['DiffService']['GetChangelistGroupDiff'](arg1);
}

export function GetSingleFileDiff(arg1) {
  return window['go']['services']['DiffService']['GetSingleFileDiff'](arg1);
}

export function SetExecutor(arg1) {
  return window['go']['services']['DiffService']['SetExecutor'](arg1);
}

export function Startup(arg1) {
  return window['go']['services']['DiffService']['Startup'](arg1);
}
