// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {git} from '../models';
import {context} from '../models';

export function CreatePatchFile(arg1:models.Changelist,arg2:string):Promise<number>;

export function CreatePatchFileForFiles(arg1:Array<string>,arg2:string):Promise<number>;

export function GenerateDefaultPatchFileName(arg1:string):Promise<string>;

export function GetChangelistGroupDiff(arg1:models.Changelist):Promise<string>;

export function GetSingleFileDiff(arg1:string):Promise<string>;

export function SetExecutor(arg1:git.Executor):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
