// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {git} from '../models';
import {context} from '../models';

export function AddRemote(arg1:string,arg2:string):Promise<void>;

export function Fetch(arg1:string,arg2:boolean):Promise<void>;

export function GetRemotes():Promise<Array<services.Remote>>;

export function GetSelectedTokenForCurrentRepo():Promise<string>;

export function GetUnpushedCommits(arg1:string):Promise<Array<string>>;

export function GetUnpushedCommitsCount(arg1:string):Promise<number>;

export function Pull(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function Push(arg1:string,arg2:string,arg3:boolean,arg4:boolean):Promise<void>;

export function RemoveRemote(arg1:string):Promise<void>;

export function SetExecutor(arg1:git.Executor):Promise<void>;

export function SetRepositoryPath(arg1:string):Promise<void>;

export function SetSelectedTokenForCurrentRepo(arg1:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
