// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRemote(arg1, arg2) {
  return window['go']['services']['RemoteService']['AddRemote'](arg1, arg2);
}

export function Fetch(arg1, arg2) {
  return window['go']['services']['RemoteService']['Fetch'](arg1, arg2);
}

export function GetRemotes() {
  return window['go']['services']['RemoteService']['GetRemotes']();
}

export function GetUnpushedCommits(arg1) {
  return window['go']['services']['RemoteService']['GetUnpushedCommits'](arg1);
}

export function GetUnpushedCommitsCount(arg1) {
  return window['go']['services']['RemoteService']['GetUnpushedCommitsCount'](arg1);
}

export function Pull(arg1, arg2, arg3) {
  return window['go']['services']['RemoteService']['Pull'](arg1, arg2, arg3);
}

export function Push(arg1, arg2, arg3, arg4) {
  return window['go']['services']['RemoteService']['Push'](arg1, arg2, arg3, arg4);
}

export function RemoveRemote(arg1) {
  return window['go']['services']['RemoteService']['RemoveRemote'](arg1);
}

export function SetExecutor(arg1) {
  return window['go']['services']['RemoteService']['SetExecutor'](arg1);
}

export function Startup(arg1) {
  return window['go']['services']['RemoteService']['Startup'](arg1);
}
