// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {services} from '../models';
import {context} from '../models';

export function CheckoutBranch(arg1:string):Promise<void>;

export function CreateBranch(arg1:string):Promise<void>;

export function DeleteBranch(arg1:string,arg2:boolean):Promise<void>;

export function GetBranches():Promise<models.BranchList>;

export function GetCommitDetail(arg1:string):Promise<models.CommitDetail>;

export function GetCommits(arg1:number,arg2:number):Promise<Array<models.Commit>>;

export function GetCurrentRepository():Promise<models.Repository>;

export function GetStatus():Promise<models.RepositoryStatus>;

export function OpenRepository(arg1:string):Promise<models.Repository>;

export function SetRemoteService(arg1:services.RemoteService):Promise<void>;

export function SetStagingService(arg1:services.StagingService):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
