// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCommits(arg1, arg2) {
  return window['go']['services']['RepositoryService']['GetCommits'](arg1, arg2);
}

export function GetCurrentRepository() {
  return window['go']['services']['RepositoryService']['GetCurrentRepository']();
}

export function GetStatus() {
  return window['go']['services']['RepositoryService']['GetStatus']();
}

export function OpenRepository(arg1) {
  return window['go']['services']['RepositoryService']['OpenRepository'](arg1);
}

export function Startup(arg1) {
  return window['go']['services']['RepositoryService']['Startup'](arg1);
}
