// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckoutBranch(arg1) {
  return window['go']['services']['RepositoryService']['CheckoutBranch'](arg1);
}

export function CheckoutCommit(arg1) {
  return window['go']['services']['RepositoryService']['CheckoutCommit'](arg1);
}

export function CherryPickCommit(arg1) {
  return window['go']['services']['RepositoryService']['CherryPickCommit'](arg1);
}

export function CreateBranch(arg1) {
  return window['go']['services']['RepositoryService']['CreateBranch'](arg1);
}

export function CreateBranchAtCommit(arg1, arg2) {
  return window['go']['services']['RepositoryService']['CreateBranchAtCommit'](arg1, arg2);
}

export function CreatePatchFile(arg1, arg2, arg3) {
  return window['go']['services']['RepositoryService']['CreatePatchFile'](arg1, arg2, arg3);
}

export function CreateTag(arg1, arg2, arg3) {
  return window['go']['services']['RepositoryService']['CreateTag'](arg1, arg2, arg3);
}

export function DeleteBranch(arg1, arg2) {
  return window['go']['services']['RepositoryService']['DeleteBranch'](arg1, arg2);
}

export function GetAuthors() {
  return window['go']['services']['RepositoryService']['GetAuthors']();
}

export function GetBranches() {
  return window['go']['services']['RepositoryService']['GetBranches']();
}

export function GetBranchesContainingCommit(arg1) {
  return window['go']['services']['RepositoryService']['GetBranchesContainingCommit'](arg1);
}

export function GetCommitDetail(arg1) {
  return window['go']['services']['RepositoryService']['GetCommitDetail'](arg1);
}

export function GetCommits(arg1, arg2, arg3) {
  return window['go']['services']['RepositoryService']['GetCommits'](arg1, arg2, arg3);
}

export function GetCurrentRepository() {
  return window['go']['services']['RepositoryService']['GetCurrentRepository']();
}

export function GetFileContentAtCommit(arg1, arg2) {
  return window['go']['services']['RepositoryService']['GetFileContentAtCommit'](arg1, arg2);
}

export function GetFileHistory(arg1, arg2, arg3) {
  return window['go']['services']['RepositoryService']['GetFileHistory'](arg1, arg2, arg3);
}

export function GetStatus() {
  return window['go']['services']['RepositoryService']['GetStatus']();
}

export function OpenRepository(arg1) {
  return window['go']['services']['RepositoryService']['OpenRepository'](arg1);
}

export function ResetBranch(arg1, arg2) {
  return window['go']['services']['RepositoryService']['ResetBranch'](arg1, arg2);
}

export function RevertCommit(arg1) {
  return window['go']['services']['RepositoryService']['RevertCommit'](arg1);
}

export function SetArchiveService(arg1) {
  return window['go']['services']['RepositoryService']['SetArchiveService'](arg1);
}

export function SetBlameService(arg1) {
  return window['go']['services']['RepositoryService']['SetBlameService'](arg1);
}

export function SetCommitService(arg1) {
  return window['go']['services']['RepositoryService']['SetCommitService'](arg1);
}

export function SetDiffService(arg1) {
  return window['go']['services']['RepositoryService']['SetDiffService'](arg1);
}

export function SetRemoteService(arg1) {
  return window['go']['services']['RepositoryService']['SetRemoteService'](arg1);
}

export function SetStagingService(arg1) {
  return window['go']['services']['RepositoryService']['SetStagingService'](arg1);
}

export function Startup(arg1) {
  return window['go']['services']['RepositoryService']['Startup'](arg1);
}
