// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckoutBranch(arg1) {
  return window['go']['services']['RepositoryService']['CheckoutBranch'](arg1);
}

export function CreateBranch(arg1) {
  return window['go']['services']['RepositoryService']['CreateBranch'](arg1);
}

export function DeleteBranch(arg1, arg2) {
  return window['go']['services']['RepositoryService']['DeleteBranch'](arg1, arg2);
}

export function GetBranches() {
  return window['go']['services']['RepositoryService']['GetBranches']();
}

export function GetCommitDetail(arg1) {
  return window['go']['services']['RepositoryService']['GetCommitDetail'](arg1);
}

export function GetCommits(arg1, arg2) {
  return window['go']['services']['RepositoryService']['GetCommits'](arg1, arg2);
}

export function GetCurrentRepository() {
  return window['go']['services']['RepositoryService']['GetCurrentRepository']();
}

export function GetStatus() {
  return window['go']['services']['RepositoryService']['GetStatus']();
}

export function OpenRepository(arg1) {
  return window['go']['services']['RepositoryService']['OpenRepository'](arg1);
}

export function SetCommitService(arg1) {
  return window['go']['services']['RepositoryService']['SetCommitService'](arg1);
}

export function SetRemoteService(arg1) {
  return window['go']['services']['RepositoryService']['SetRemoteService'](arg1);
}

export function SetStagingService(arg1) {
  return window['go']['services']['RepositoryService']['SetStagingService'](arg1);
}

export function Startup(arg1) {
  return window['go']['services']['RepositoryService']['Startup'](arg1);
}
