// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {context} from '../models';

export function GetCurrentRepository():Promise<models.Repository>;

export function GetStatus():Promise<models.RepositoryStatus>;

export function OpenRepository(arg1:string):Promise<models.Repository>;

export function Startup(arg1:context.Context):Promise<void>;
