// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';

export function Commit(arg1:string,arg2:boolean):Promise<void>;

export function GetFileDiff(arg1:string,arg2:boolean):Promise<string>;

export function GetStatus():Promise<services.WorkingDirectoryStatus>;

export function GetStatusForSpecificFilePaths(arg1:Array<string>):Promise<Array<services.FileStatus>>;

export function RevertFileChanges(arg1:string,arg2:services.RevertOptions):Promise<void>;

export function StageAll():Promise<void>;

export function StageFile(arg1:string):Promise<void>;

export function StageMultipleFilePaths(arg1:Array<string>):Promise<void>;

export function UnstageAll():Promise<void>;

export function UnstageFile(arg1:string):Promise<void>;

export function UnstageMultipleFilePaths(arg1:Array<string>):Promise<void>;
