// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetStatus() {
  return window['go']['services']['StagingService']['GetStatus']();
}

export function StageAll() {
  return window['go']['services']['StagingService']['StageAll']();
}

export function StageFile(arg1) {
  return window['go']['services']['StagingService']['StageFile'](arg1);
}

export function UnstageAll() {
  return window['go']['services']['StagingService']['UnstageAll']();
}

export function UnstageFile(arg1) {
  return window['go']['services']['StagingService']['UnstageFile'](arg1);
}
