import type { ComponentType, SVGProps } from 'react';
import {
  TypeScript,
  Js,
  Reactjs,
  Reactts,
  Go,
  Python,
  Ruby,
  Rust,
  Java,
  Kotlin,
  Swift,
  Csharp,
  Cplus,
  CLang,
  PHP,
  Sass,
  Markdown,
  MDX,
  Yaml,
  XML,
  Image,
  Video,
  Audio,
  Document,
  Database,
  Git,
  Docker,
  Vue,
  Svelte,
  Angular,
  Astro,
  Next,
  Nest,
  Nuxt,
  Vite,
  Webpack,
  Gulp,
  Gradle,
  NPM,
  Yarn,
  PNPM,
  Text,
  Shell,
  Prisma,
  Graphql,
  Proto,
  Terraform,
  Tailwind,
  PostCSS,
  Eslint,
  Prettier,
  Jest,
  Vitest,
  Cypress,
  Storybook,
  Tsconfig,
  EditorConfig,
  License,
  Ignore,
  PDF,
  Csv,
  SVG,
  Font,
  Lock,
  Dts,
  Patch,
  CodeBlue,
} from '@react-symbols/icons';

type IconComponent = ComponentType<SVGProps<SVGSVGElement>>;

const DEFAULT_ICON_SIZE = 20;

const extensionToIconMap: Record<string, IconComponent> = {
  ts: TypeScript,
  tsx: Reactts,
  js: Js,
  jsx: Reactjs,
  mjs: Js,
  cjs: Js,
  go: Go,
  py: Python,
  pyw: Python,
  pyx: Python,
  rb: Ruby,
  rs: Rust,
  java: Java,
  jav: Java,
  kt: Kotlin,
  kts: Kotlin,
  swift: Swift,
  cs: Csharp,
  cpp: Cplus,
  cxx: Cplus,
  cc: Cplus,
  c: CLang,
  h: CLang,
  hpp: Cplus,
  php: PHP,
  css: Sass,
  scss: Sass,
  sass: Sass,
  less: Sass,
  md: Markdown,
  mdx: MDX,
  json: CodeBlue,
  jsonc: CodeBlue,
  json5: CodeBlue,
  yml: Yaml,
  yaml: Yaml,
  xml: XML,
  html: XML,
  svg: SVG,
  png: Image,
  jpg: Image,
  jpeg: Image,
  gif: Image,
  webp: Image,
  ico: Image,
  bmp: Image,
  mp4: Video,
  mov: Video,
  avi: Video,
  webm: Video,
  mp3: Audio,
  wav: Audio,
  ogg: Audio,
  flac: Audio,
  txt: Text,
  log: Text,
  pdf: PDF,
  csv: Csv,
  sql: Database,
  db: Database,
  sqlite: Database,
  gitignore: Ignore,
  gitattributes: Git,
  gitmodules: Git,
  dockerignore: Docker,
  dockerfile: Docker,
  sh: Shell,
  bash: Shell,
  zsh: Shell,
  fish: Shell,
  vue: Vue,
  svelte: Svelte,
  prisma: Prisma,
  graphql: Graphql,
  gql: Graphql,
  proto: Proto,
  tf: Terraform,
  tfvars: Terraform,
  lock: Lock,
  'package-lock': NPM,
  'yarn.lock': Yarn,
  'pnpm-lock': PNPM,
  npmrc: NPM,
  yarnrc: Yarn,
  'package.json': NPM,
  'tsconfig.json': Tsconfig,
  'jest.config': Jest,
  'vitest.config': Vitest,
  'cypress.json': Cypress,
  'vite.config': Vite,
  'webpack.config': Webpack,
  'tailwind.config': Tailwind,
  'postcss.config': PostCSS,
  eslintrc: Eslint,
  eslintignore: Eslint,
  prettierrc: Prettier,
  prettierignore: Prettier,
  editorconfig: EditorConfig,
  license: License,
  'license.md': License,
  'license.txt': License,
  'docker-compose': Docker,
  'next.config': Next,
  'nuxt.config': Nuxt,
  'angular.json': Angular,
  'nest-cli.json': Nest,
  'astro.config': Astro,
  gulpfile: Gulp,
  'build.gradle': Gradle,
  'pom.xml': Gradle,
  '.storybook': Storybook,
  dts: Dts,
  patch: Patch,
  ttf: Font,
  woff: Font,
  woff2: Font,
  eot: Font,
  otf: Font,
};

export function getFileIcon(fileName: string): IconComponent {
  const lowerFileName = fileName.toLowerCase();

  if (extensionToIconMap[lowerFileName]) {
    return extensionToIconMap[lowerFileName];
  }

  const extension = lowerFileName.split('.').pop() || '';

  return extensionToIconMap[extension] || Document;
}

export { DEFAULT_ICON_SIZE };
