// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCommitService() {
  return window['go']['main']['App']['GetCommitService']();
}

export function GetRepositoryService() {
  return window['go']['main']['App']['GetRepositoryService']();
}

export function GetStagingService() {
  return window['go']['main']['App']['GetStagingService']();
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function SelectSaveDirectory() {
  return window['go']['main']['App']['SelectSaveDirectory']();
}
