// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {models} from '../models';

export function GetRepositoryService():Promise<services.RepositoryService>;

export function OpenDirectoryDialog():Promise<models.Repository>;
