// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {models} from '../models';

export function GetArchiveService():Promise<services.ArchiveService>;

export function GetChangelistService():Promise<services.ChangelistService>;

export function GetCommitService():Promise<services.CommitService>;

export function GetDiffService():Promise<services.DiffService>;

export function GetRepositoryService():Promise<services.RepositoryService>;

export function GetStagingService():Promise<services.StagingService>;

export function OpenDirectoryDialog():Promise<models.Repository>;

export function SaveFileDialog(arg1:string):Promise<string>;

export function SelectSaveDirectory():Promise<string>;
