// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppConfigService() {
  return window['go']['main']['App']['GetAppConfigService']();
}

export function GetArchiveService() {
  return window['go']['main']['App']['GetArchiveService']();
}

export function GetBlameService() {
  return window['go']['main']['App']['GetBlameService']();
}

export function GetChangelistService() {
  return window['go']['main']['App']['GetChangelistService']();
}

export function GetCommitService() {
  return window['go']['main']['App']['GetCommitService']();
}

export function GetCredentialsService() {
  return window['go']['main']['App']['GetCredentialsService']();
}

export function GetDiffService() {
  return window['go']['main']['App']['GetDiffService']();
}

export function GetRepositoryService() {
  return window['go']['main']['App']['GetRepositoryService']();
}

export function GetStagingService() {
  return window['go']['main']['App']['GetStagingService']();
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function SaveFileDialog(arg1) {
  return window['go']['main']['App']['SaveFileDialog'](arg1);
}

export function SelectSaveDirectory() {
  return window['go']['main']['App']['SelectSaveDirectory']();
}
